version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - npm i sonarqube-scanner
        - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
        - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
        - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
        - sonar-scanner -Dsonar.host.url=https://sonarcloud.io/organizations/adarsha1999/projects -Dsonar.login=6210789d545c3232998515272cb0184f4bdbbb8e
  build:
    commands:
        - echo Build started 
        - ng build
        

artifacts:
    files:
        - '**/*'
    type: zip
    base-directory: 'dist*'
    discard-paths: yes
